# Tell us to put the chickens away at sunset
#
- alias: Chicken reminder at sunset
  trigger:
    - event: sunset
      offset: 00:00:00
      platform: sun

  action:
    - service: script.speech_engine
      data_template:
        value1: 'Time to put the chickens away!'
